title: Lim Lab
description: The Lim Lab at UW–Madison studies how human cells protect and replicate the ends of their chromosomes, using structural biology, single-molecule biophysics, and biochemistry.
url: "https://tallgeese84.github.io"
baseurl: "/limlab-website"

future: true
